export const propertyInsurance = "Property Insurance";
export const appartment = "Appartment";
export const house = "House";
export const car2 = "2 door car";
export const car3 = "3 door car";
export const car4 = "4 door car";
export const car5 = "5 door car";
export const social = "Social Security Number";
export const work = "Work Permit";
export const flat = "Flat";
export const drivers = "Drivers License"
export const scooter = "Scooter";
export const bike = "Bike";
export const motorcycle = "Motorcycle"
export const motorInsurance = "Motorcycle Insurance";
export const massage = "Massage Qualification Certificate";
export const liability = "Liability Insurance";
export const storage = "Storage Space";
export const garage = "Garage";
export const paypal = "PayPal Account";